export const FooterLink2 = [
  {
    title: "Subjects",
    links: [
      { title: "Accounting & Finance", link: "/welcome" },
      { title: "Admin Support", link: "/welcome" },
      { title: "Customer Service", link: "/welcome" },
      { title: "Data Entry", link: "/welcome" },
      { title: "Graphic Design", link: "/welcome" },
      { title: "Legal", link: "/welcome" },
      { title: "Marketing", link: "/welcome" },
      { title: "Mobile App Development", link: "/welcome" },
      { title: "Photography", link: "/welcome" },
      { title: "Project Management", link: "/welcome" },
      { title: "Sales", link: "/welcome" },
      { title: "Software Development", link: "/welcome" },
      { title: "Translation", link: "/welcome" },
      { title: "Video Editing", link: "/welcome" },
      { title: "Virtual Assistant", link: "/welcome" },
      { title: "Writing", link: "/welcome" },
    ],
  },
  {
    title: "Languages",
    links: [
      { title: "Bash", link: "/bash" },
      { title: "C++", link: "/c++" },
      { title: "C#", link: "/csharp" },
      { title: "Go", link: "/go" },
      { title: "HTML & CSS", link: "/html-css" },
      { title: "Java", link: "/java" },
      { title: "JavaScript", link: "/javascript" },
      { title: "Kotlin", link: "/kotlin" },
      { title: "PHP", link: "/php" },
      { title: "Python", link: "/python" },
      { title: "R", link: "/r" },
      { title: "Ruby", link: "/ruby" },
      { title: "SQL", link: "/sql" },
      { title: "Swift", link: "/swift" },
    ],
  },
  {
    title: "Career Building",
    links: [
      { title: "Freelancer Resources", link: "/freelancer-resources" },
      { title: "Skill Development", link: "/skill-development" },
      { title: "Networking", link: "/networking" },
      { title: "Success Stories", link: "/success-stories" },
      {
        title: "Professional Certification",
        link: "/professional-certification",
      },
      { title: "Community Forums", link: "/community-forums" },
      { title: "Full Catalog", link: "/full-catalog" },
      { title: "Beta Content", link: "/beta-content" },
    ],
  },
];
